### ISSUE TITLE
repository structure is broken?

### ISSUE THREAD

**Issue by bigwheel** [rcongiu/Hive-JSON-Serde#107]
I see "Failed to load latest commit information." message from github in this page.
https://github.com/rcongiu/Hive-JSON-Serde/tree/develop/json/src/main/java/org/openx/data/jsonserde/json

**Comment by rcongiu** [comment]
what happens if you reload ? Sounds like a github temporary issue, I can open that page just fine.

**Comment by bigwheel** [comment]
hm, I saw that message such as https://twitter.com/jcspray/status/573869986533535744 certainly 2 hours before, but I cant see that now.

Anyway, it seems this is a github issue. Sorry for wrong issue, i closed this.
