### ISSUE TITLE
Question regarding which jar to use.

### ISSUE THREAD

**Issue by rae89** [rcongiu/Hive-JSON-Serde#113]
Hello.  I am running vanilla hadoop and hive on my ubuntu machine. Will this only work for the cloudera version of hadoop and hive? Also, for my case, which JAR should I be using? And is it necessary to build the json, json-serde, and cdh4 and ch5 JARs, or do I just need to build the one I need? Thanks.

**Comment by rcongiu** [comment]
So, which one you need basically depends on the version of hive you're using. The serde should work also on non-cloudera, but at the time I was using the cloudera distribution (it also was the only one hadoop distribution at the time) so I tuned the serde to that. Which version of hadoop and hive are you using ? You can build the serde for a specific version using mvn -Dcdh.hadoop.version=...

**Comment by rae89** [comment]
Thanks for the reply. I am using hadoop 2.7.0 and hive 1.2.1.

**Comment by rae89** [comment]
So if I use mvn -Dcdh.hadoop.version=... then which JAR from which folder [json, json-serde, and cdh4 and cdh5] should I use?

**Comment by rcongiu** [comment]
The serde is built under json-serde/target. -------------------------------------------------------
"Good judgment comes from experience. 
Experience comes from bad judgment"
------------------------------------------------------- 


     On Thursday, August 20, 2015 12:14 PM, rae89 <notifications@github.com> wrote:
   

 So if I use mvn -Dcdh.hadoop.version=... then which JAR from which folder [json, json-serde, and cdh4 and cdh5] should I use?—
