### ISSUE TITLE
Wrong datatype causes crash, ignore.malformed.json does not help

### ISSUE THREAD

**Issue by ChuckConnell** [rcongiu/Hive-JSON-Serde#12]
A value with a wrong datatype causes the generated MR job to crash. ignore.malformed.json does not seem to fix it.

Here is the sample data, mixed2.json

```
{"f1":"hello", "f2":7}
{"f1":"goodbye", "f2":8}
{"f1":"this", "f2":9}
{"f1":"that", "f2":"ten"}
```

Here is the sample Hive script, mixed2.hive. The first query (on f1) works. The other queries (on \* and f2) crash. It would be nice to see NULL or something else. The get_json_object() function actually returns the bad string, so it prints "ten"!

```
drop table mixed2;

create table mixed2 (f1 string, f2 int)
row format serde 'org.openx.data.jsonserde.JsonSerDe'
with serdeproperties ("ignore.malformed.json" = "true")
stored as textfile;

load data inpath '/tmp/mixed2.json' overwrite into table mixed2;

select f1 from mixed2;

select f2 from mixed2;

select * from mixed2;
```

**Comment by Cord-Thomas** [comment]
I believe I am having somewhat of a similar problem.  I have a collection of JSON records where one field is misbehaving and I am not sure the best way to handle it in Hive.  So far, have had great luck with this SerDe.

authors field is sometimes a single string and sometimes an array (thanks data provider).   I typed it as an array<string> but obviously hive complains when it finds a record that is just a string (HiveException: java.lang.ClassCastException: java.lang.String cannot be cast to org.openx.data.jsonserde.json.JSONArray).  I have ignore.malformed.json=true, but obviously this is not malformed.  

I read this and a few other issues but don't see exactly the way i am meant to handle this.  Obviously a relatively novice Hiver here though quite familiar with json.

**Comment by rcongiu** [comment]
Mmm... It should be relatively easy to change it so if you have an array field and you got a scalar, it converts it to a 1-element array. I think that would solve your problem.

**Comment by rcongiu** [comment]
Ok...I actually pushed a change that should work for you...it's in the devel branch and should work fine (I added a unit test too).  See https://github.com/rcongiu/Hive-JSON-Serde#promoting-a-scalar-to-an-array and please let me know if it works for you.

**Comment by Cord-Thomas** [comment]
Thank you Roberto; great stuff.

I have to wait for someone to load the jar for me so it may be until Monday when i can confirm this fixes my issue as i suspect it does.

Cord

**Comment by Cord-Thomas** [comment]
Actually,

I have installed on test host and fairly certain i did that correctly.   Attached is a sample dataset that fails and here is my schema.  This is publicly available data.

Does this work for you?   Or am i doing something really wrong?

Executing this query fails starting at limit 6, which is CB-142

select document_number, authors from pubs limit 6;

Failed with exception java.io.IOException:org.apache.hadoop.hive.ql.metadata.HiveException: java.lang.ClassCastException: java.lang.String cannot be cast to org.openx.data.jsonserde.json.JSONArray

Cord

ADD JAR …. hive/lib/json-serde-1.3.8-SNAPSHOT-jar-with-dependencies.jar;

CREATE EXTERNAL TABLE pubs (
   document_number STRING,
   document_title STRING,
   series STRING,
   inv_status STRING,
   product_formats STRING,
   product_date SMALLINT,
   long_abstract STRING,
   short_abstract STRING,
   categories ARRAY<STRING>,
   research_areas ARRAY<STRING>,
   primary_research_area STRING,
   asset_links_path ARRAY<STRING>,
   authors ARRAY<STRING>,
   author_types ARRAY<STRING>,
   publisher STRING,
   fileReference STRING,
   comments STRING
)
ROW FORMAT SERDE 'org.openx.data.jsonserde.JsonSerDe'
WITH SERDEPROPERTIES ("ignore.malformed.json" = "true")
LOCATION '/data/pubs';

**Comment by Cord-Thomas** [comment]
Check that - it would seem i did not properly reload the SerDe library.  This resolved my issue.  Thank you Roberto.

**Comment by rcongiu** [comment]
yay! You're welcome.

**Comment by dblock** [comment]
I think the OP's isssue is fixed, this can be closed?

**Comment by Cord-Thomas** [comment]
Yes
