### ISSUE TITLE
Add an option enabling translation of certain characters (from stackoverflow.com issue)

### ISSUE THREAD

**Issue by frbattid** [rcongiu/Hive-JSON-Serde#131]
As discussed in [stackoverflow.com](http://stackoverflow.com/questions/35344480/hive-select-column-with-non-alphanumeric-characters) (if I've understood well):

It would be great the serde could be configured in order certain characters within the query string are converted to other characters. This would be very useful when, for instance, dots are used in the real Json data fields, but Hive is not allowing to use such dots in the table column names.

**Comment by rcongiu** [comment]
I just pushed the changes in the develop branch. Please refer to the README for how to use it (https://github.com/rcongiu/Hive-JSON-Serde#mapping-names-with-dots)
