### ISSUE TITLE
Failed to build Maven Jar

### ISSUE THREAD

**Issue by vijaykumar243** [rcongiu/Hive-JSON-Serde#137]
Can you please help me with the jar which is used for Json serde
There is a problem while building  the jar.

Error :

openx-json-serde .................................. FAILURE [1:22.936s] [INFO] json .............................................. SKIPPED [INFO] json-cdh4-shim .................................... SKIPPED [INFO] json-cdh5-shim .................................... SKIPPED [INFO] json-serde-main ................................... SKIPPED [INFO] json-udf .......................................... SKIPPED [INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1:23.108s
[INFO] Finished at: Tue Mar 01 16:00:45 IST 2016 [INFO] Final Memory: 4M/15M [INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:buildnumber-maven-plugin:1.1:create (default) on project json-serde-parent: Execution default of goal org.codehaus.mojo:buildnumber-maven-plugin:1.1:create failed: Plugin org.codehaus.mojo:buildnumber-maven-plugin:1.1 or one of its dependencies could not be resolved: The following artifacts could not be resolved: org.apache.maven.scm:maven-scm-manager-plexus:jar:1.7, regexp:regexp:jar:1.3: Could not transfer artifact org.apache.maven.scm:maven-scm-manager-plexus:jar:1.7 from/to central (http://repo.maven.apache.org/maven2): No response received after 60000 -> [Help 1]

**Comment by rcongiu** [comment]
Sounds like a temporary connectivity with the maven repo, but you can download a precompiled binary here http://www.congiu.net/hive-json-serde/
