### ISSUE TITLE
Parsing escaped JSON from attributes

### ISSUE THREAD

**Issue by d-robin** [rcongiu/Hive-JSON-Serde#154]
Hello,

One of the JSON attributes contain escaped JSON data that is being treated as a string. Though it is an escaped JSON object, an array. Is there a way to deal with it using the library?

A simplified sample: {"Message": "[{\"Key\":\"GetService1\",\"ResponseTime\":\"12\"},{\"Key\":\"ServiceOperation\",\"ResponseTime\":\"2\"},{\"Key\":\"Service\",\"ResponseTime\":\"16\"}]" }

This is a case specific problem and not an issue. I've been looking up hard to deal with it. Any help or recommendation is greatly appreciated.

**Comment by rcongiu** [comment]
Eh, no , that is indeed a string and the serde has no way to know it's a JSON string.  Have you tried extracting the json using get_json_object ?

**Comment by d-robin** [comment]
I tried that. It seems to expect well formed JSON object string too. :-/

**Comment by d-robin** [comment]
Hello Roberto, I finally solved it by converting the JSON string to Hive Array using regex transformations! Thanks :-)
