### ISSUE TITLE
Stuck on maven build: working directory

### ISSUE THREAD

**Issue by pmorelli92** [rcongiu/Hive-JSON-Serde#161]
Hi guys, I am having a problem trying to compile the jar using maven (for HDP 2.3).
In the first image we can see which version of maven and java I am using:

![version](https://cloud.githubusercontent.com/assets/19840466/18063848/26a14076-6e03-11e6-8a1e-61a40f7fb73e.png)

(I've also tried using maven 3.39 and java 1.8.92 and got stuck in the same part)

Image of the maven build:

![stuck](https://cloud.githubusercontent.com/assets/19840466/18063903/5a083a6e-6e03-11e6-8b13-8068c362d93d.png)

The code I downloaded is from the master branch.

Can you guys lend me a hand, please?
Regards!

**Comment by rcongiu** [comment]
it just hangs there ? I am using mvn 3.39 on windows and can compile fine from master, I'd guess it's something with your environment and/or connectivity with github.

What's the actual command you are issuing to maven ?

**Comment by pmorelli92** [comment]
`-mvn -Phdp23 clean package`

However I tried all the compilation profiles in the readme and I got the same result.
I will try compiling from my house in case it is related to my environment.

Is there some maven log that I can share in order to see if there is a problem?

**Comment by pmorelli92** [comment]
Hi @rcongiu, I was able to compile it in the pc of my house. Thanks for the attention!
