### ISSUE TITLE
duplicate key mapping issue

### ISSUE THREAD

**Issue by hidarapaneni** [rcongiu/Hive-JSON-Serde#163]
hi @rcongiu ,

I tried the approach that was mentioned in one of the issue  but still giving me duplicate issue. Please advice.

Here are details : json-serde-1.3.8-SNAPSHOT-jar-with-dependencies.jar

sample json : {"Time":"forme","time":"foryou"}

ddl : create external table sample_dup1(duptime1 string, duptime2 string) ROW FORMAT SERDE
'org.openx.data.jsonserde.JsonSerDe'
WITH SERDEPROPERTIES (
"mapping.duptime1"="Time",
"mapping.duptime2"="time")
location '/user/hive/warehouse/samp_dup_test/';

**Comment by rcongiu** [comment]
this is dublicate as #156 . I just commited a change in that ticket to fix this.
