### ISSUE TITLE
Compilation of Hive-JSON-Serde

### ISSUE THREAD

**Issue by tusharkudal** [rcongiu/Hive-JSON-Serde#179]
How to compile Hive-JSON-Serde for Apache Hadoop 1.2.1?

**Comment by rcongiu** [comment]
You can override the hive version like this:

```
 mvn -Dcdh4.hive.version=1.2.1 package
```

**Comment by rcongiu** [comment]
I just did some improvements in the maven project, now you can build the SerDe for hadoop 1.2.1 using

```
 mvn -Dcdh5.hadoop.version=1.2.1 -Dhadoop.dependency=hadoop-core clean package
```

The issue is that Cloudera went from the 0.x directly to the 2.x version, so I had to make some changes in the project definition to accept a non-cloudera version for the dependencies.

**Comment by tusharkudal** [comment]
Thanks!
