### ISSUE TITLE
FAILED: Execution Error

### ISSUE THREAD

**Issue by medicharlachiranjeevi** [rcongiu/Hive-JSON-Serde#216]
FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.DDLTask. org/apache/hadoop/hive/serde2/SerDe
Hadoop version:2.6.5  
Hive version: 2.3.5
JAR: json-serde-1.3.6-SNAPSHOT-jar-with-dependencies.jar

**Comment by rcongiu** [comment]
org/apache/hadoop/hive/serde2/SerDe means you're not actually using my SerDe but the stock hadoop one.
