### ISSUE TITLE
How can I read the following json from your serde?

### ISSUE THREAD

**Issue by Aekansh-Ak** [rcongiu/Hive-JSON-Serde#224]
[
   {
      "liked":"true",
      "user_id":"101",
      "video_end_type":"3",
      "minutes_played":"3",
      "video_id":"101",
      "geo_cd":"AP",
      "channel_id":"11",
      "creator_id":"101",
      "timestamp":"07/05/2019 01:36:35",
      "disliked":"true"
   },
   {
      "liked":"true",
      "user_id":"102",
      "video_end_type":"null",
      "minutes_played":"4",
      "video_id":"102",
      "geo_cd":"AP",
      "channel_id":"12",
      "creator_id":"102",
      "timestamp":"15/04/2019 17:04:00",
      "disliked":"true"
   }
]

**Comment by rcongiu** [comment]
It must be one record per line for the serde to work
