### ISSUE TITLE
Keywords as JSON properties

### ISSUE THREAD

**Issue by sixtus** [rcongiu/Hive-JSON-Serde#24]
I am unable to figure out how to read "timestamp" from my json, as hive 

FAILED: ParseException line 3:2 mismatched input 'timestamp' expecting Identifier near ',' in column specification

is there an "as ts" syntax?

**Comment by Gcsaniz** [comment]
How can this be done in the JSON input?

For example:
{ "IsDeleted": true } SerDe output creates a boolean field
{ "BillingLatitude": 0 } SerDe output creates an int field
{ "Message": "Hello World" } SerDe output creates a string field
{ "LastActivityTime": "1980-01-01 00:00:00.0" } SerDe output DOES NOT create a timestamp field rather it creates a string field

What value in the JSON input would drive the creation of a timestamp field?

**Comment by rcongiu** [comment]
You have to declare it as timestamp in the hive table. Internally, the SerDe uses the JSON library to parse the JSON object, in this case to string, then when hive requests the timestamp, a conversion is made from string to timestamp.
