### ISSUE TITLE
parse complex json file failed

### ISSUE THREAD

**Issue by timeforce** [rcongiu/Hive-JSON-Serde#81]
my json file is like: {"lastTimestamp": xxxxxxx, "obj":[{"description":"xxxxx", "timestamp": xxxxxxxx, "prefix":"xxx", "tags":{}, "encoding":"xxxx"}], "sucess":"xxxx", "totalResults":"xxx", "elapsedms":"xxx"}

And I tried:

hive> create table json(lastTimestamp string, obj array<struct<description:string, timestamp:string,prefix:string,  encoding:string>>, success string,totalResults string,elapsedms string)
    > ROW FORMAT SERDE 'org.openx.data.jsonserde.JsonSerDe';

But got error:

FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.DDLTask. Could not initialize class org.openx.data.jsonserde.objectinspector.JsonObjectInspectorFactory

I omitted "tags":{} as I don't know how to deal with it in the schema. Is that the root cause?

Thanks

**Comment by rcongiu** [comment]
Closing as no answer to my observation.
