### ISSUE TITLE
Fields having Timestamp DataType are not getting written to File in Serialize of JsonSerde

### ISSUE THREAD

**Issue by appanasatya** [rcongiu/Hive-JSON-Serde#91]
Timestamp field and value is not even reflecting in the file that hive external table is pointing to.

```
Create external table satya(a int , b timestamp)
ROW FORMAT SERDE 'org.openx.data.jsonserde.JsonSerDe'
location '/tmp/satya';
```

```
insert into table satya select 1,1411286918 from different_table limit 1;
insert into table satya select 1,1411286918.986 from different_table limit 1;
insert into table satya select 1,"2014-09-16 12:13:14.0" from different_table limit 1;
```

[Hive Timestamp DataType Reference](https://cwiki.apache.org/confluence/display/Hive/LanguageManual+Types#LanguageManualTypes-timestamp)

```
hadoop fs -cat /tmp/satya;
{"a":1}
```

**Comment by bigwheel** [comment]
Because there is no case for TIMESTAMP in there https://github.com/rcongiu/Hive-JSON-Serde/blob/develop/json-serde/src/main/java/org/openx/data/jsonserde/JsonSerDe.java#L296-L326 .
Then, default value 'null' is used for TIMESTAMP columns.

**Comment by rcongiu** [comment]
@bigwheel  is right, timestamp is missing in serialization.
I just pushed a fix in the  development branch, have a look.
I did a brief test and it looks like it's working:
{"b":"2014-09-16 12:13:14","a":3}

**Comment by dennyriadi** [comment]
@appanasatya I came across the same issue recently and here is the PR for it https://github.com/rcongiu/Hive-JSON-Serde/pull/143. Hopefully @rcongiu will have time to review it.

**Comment by rcongiu** [comment]
I did merge it and it should be working. Closing, reopen if you still have the issue.
